export const metadata = { title: 'Privacy · MCG Support' };

export default function PrivacyPage() {
  return (
    <article className="container-page max-w-3xl py-10 prose prose-slate dark:prose-invert">
      <h1>Privacy notice</h1>
      <p>
        MCG Career College (&quot;MCG&quot;, &quot;we&quot;) is committed to safeguarding your
        personal information in accordance with the federal{' '}
        <em>Personal Information Protection and Electronic Documents Act</em> (PIPEDA) and
        applicable Alberta privacy guidance.
      </p>
      <h2>What we collect</h2>
      <ul>
        <li>Identity and enrolment data, synced from CampusLogin (our student information system).</li>
        <li>Conversations you have with the MCG Assistant.</li>
        <li>Support tickets and messages you exchange with our advisors.</li>
        <li>Technical data necessary to operate the portal (session cookies, IP address, request logs).</li>
      </ul>
      <h2>Why we collect it</h2>
      <p>
        To provide you with student support — answer questions about your enrolment, route
        tickets to the right advisor, and improve the help we provide.
      </p>
      <h2>Where it lives</h2>
      <p>
        Data is stored in MCG&apos;s database hosted in Canada. AI completions are routed
        through Anthropic Claude under a data-processing agreement that prohibits training on
        customer data. Embeddings are generated by OpenAI under the same terms.
      </p>
      <h2>Your rights</h2>
      <ul>
        <li><strong>Access:</strong> download your data at any time from <a href="/account">My account</a>.</li>
        <li><strong>Correction:</strong> open a ticket with the &quot;Account&quot; category.</li>
        <li><strong>Deletion:</strong> after withdrawal or graduation you can request deletion of personal data. Audit logs are retained for 7 years per Alberta records guidance.</li>
        <li><strong>Complaint:</strong> contact <a href="mailto:privacy@mcgcollege.com">privacy@mcgcollege.com</a>. If unresolved, you may escalate to the federal Privacy Commissioner.</li>
      </ul>
      <p className="text-sm text-muted-foreground">
        Final copy pending legal review before public launch.
      </p>
    </article>
  );
}
